#!/usr/bin/env python3
"""Build public/soundtrack.wav and src/data/envelope.ts from a local copy of the track.

The soundtrack is De Hofnar's "Zonnestraal" and is not committed; supply your own file:

    python3 scripts/prepare-audio.py ~/Music/Zonnestraal.mp3

Edit: 44.000 s → 90.358 s (the count-in, the horns phrase, the drop, and seven bars of
groove), then the track's own riser bar (74.998 s) so the final lockup lands on its impact.
The pieces meet on a bar line with a 12 ms equal-power crossfade, and a 2.1 s fade follows
the impact. Requires ffmpeg, numpy and scipy.
"""

import base64
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from scipy.io import wavfile
from scipy.signal import butter, sosfiltfilt

ROOT = Path(__file__).resolve().parent.parent
GRID_REF = 37.558  # beat 0 in the original track
BEAT = 0.48  # 125 BPM
START = 44.0  # "One" lands on beat 14
DURATION = 50.6
FPS = 60


def beat(k: float) -> float:
    return GRID_REF + BEAT * k


def decode(src: Path) -> tuple[int, np.ndarray]:
    with tempfile.TemporaryDirectory() as tmp:
        wav = Path(tmp) / "full.wav"
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(src),
             "-map", "0:a", "-ac", "2", "-ar", "48000", "-c:a", "pcm_f32le", str(wav)],
            check=True,
        )
        sr, x = wavfile.read(wav)
    return sr, x.astype(np.float64)


def build(sr: int, x: np.ndarray) -> np.ndarray:
    splice_v = beat(110) - START
    seg1 = x[round(START * sr): round(beat(110) * sr)]
    seg2 = x[round(beat(78) * sr): round((beat(78) + DURATION - splice_v) * sr)]
    xf = int(0.012 * sr)
    tail = x[round(beat(110) * sr): round(beat(110) * sr) + xf]
    th = np.linspace(0, np.pi / 2, xf)[:, None]
    y = np.concatenate([seg1, tail * np.cos(th) + seg2[:xf] * np.sin(th), seg2[xf:]])
    fade_in = int(0.006 * sr)
    y[:fade_in] *= np.linspace(0, 1, fade_in)[:, None]
    t = np.arange(len(y)) / sr
    impact = splice_v + (beat(82) - beat(78))
    u = np.clip((t - (impact + 0.22)) / (DURATION - impact - 0.22), 0, 1)
    y *= ((1 - u) ** 2.2)[:, None]
    # Sample peak 0.86 keeps the true peak near -1.2 dBTP after AAC encoding.
    return y * (0.86 / np.abs(y).max())


def envelopes(sr: int, y: np.ndarray) -> str:
    mono = y.mean(1)
    low = sosfiltfilt(butter(4, [35, 150], btype="band", fs=sr, output="sos"), mono)
    hop = sr // FPS
    n = len(mono) // hop
    rms = np.array([np.sqrt(np.mean(low[i * hop:(i + 1) * hop] ** 2)) for i in range(n)])
    db = 20 * np.log10(rms + 1e-6)
    onset = np.maximum(0, np.diff(db, prepend=db[0]))
    onset /= np.percentile(onset[onset > 0], 98)
    kick = np.zeros(n)
    prev = 0.0
    for i in range(n):
        prev = max(min(1.0, onset[i]), prev * 0.86)
        kick[i] = prev
    level = np.clip((db - np.percentile(db, 10)) / (np.percentile(db, 99) - np.percentile(db, 10)), 0, 1)

    def b64(a: np.ndarray) -> str:
        return base64.b64encode(np.round(np.clip(a, 0, 1) * 255).astype(np.uint8).tobytes()).decode()

    return f"""// Per-frame (60 fps) low-end envelopes of public/soundtrack.wav, 0–255, base64.
// Generated by scripts/prepare-audio.py. kick: onset pulses of the 35–150 Hz band; level: its loudness.
const decode = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0))
const kick = decode(
  '{b64(kick)}'
)
const level = decode(
  '{b64(level)}'
)
const at = (a: Uint8Array, frame: number) =>
  (a[Math.max(0, Math.min(a.length - 1, Math.round(frame)))] ?? 0) / 255
export const kickAt = (t: number) => at(kick, t * 60)
export const levelAt = (t: number) => at(level, t * 60)
"""


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    sr, x = decode(Path(sys.argv[1]).expanduser())
    y = build(sr, x)
    wavfile.write(ROOT / "public" / "soundtrack.wav", sr, y.astype(np.float32))
    (ROOT / "src" / "data" / "envelope.ts").write_text(envelopes(sr, y))
    print(f"Wrote public/soundtrack.wav ({len(y) / sr:.3f} s) and src/data/envelope.ts")


if __name__ == "__main__":
    main()
