import { personaIdentity } from '@/lib/journeys/persona-identity'
import { independentPersonas } from '@/lib/journeys/independent-personas'
import {
  techPosterPersonas,
  techPosterPronouns
} from '@/lib/journeys/tech-poster-personas'
import { oneLiner } from './one-liners'

const profiles = [
  {
    id: 'permissionless-innovation-optimist',
    featured: true,
    name: 'Andrew McAfee',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/amcafee',
    avatar: '/personas/mcafee.jpg',
    initials: 'AM',
    stance: 'Let innovation flourish. Respond to real harms.',
    tone: 'bloom'
  },
  {
    id: 'alignment-philosopher',
    featured: true,
    name: 'Joe Carlsmith',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/jkcarlsmith',
    avatar: '/personas/carlsmith.jpg',
    initials: 'JC',
    stance: 'Preserve the chance of a much better future.',
    tone: 'middle'
  },
  {
    id: 'rationalist-safety-advocate',
    featured: true,
    name: 'Scott Alexander',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/slatestarcodex',
    avatar: '/personas/alexander.jpg',
    initials: 'SA',
    stance: 'Take the risk seriously. Give safety time.',
    tone: 'middle'
  },
  {
    id: 'takeoff-forecaster',
    featured: true,
    name: 'Daniel Kokotajlo',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/DKokotajlo',
    avatar: '/personas/kokotajlo.jpg',
    initials: 'DK',
    stance: 'Do not race through an intelligence explosion.',
    tone: 'doom'
  },
  {
    id: 'institutional-growth-optimist',
    featured: true,
    name: 'Tyler Cowen',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/tylercowen',
    avatar: '/personas/cowen.jpg',
    initials: 'TC',
    stance: 'More intelligence. Better institutions.',
    tone: 'bloom'
  },
  {
    id: 'superintelligence-stop-advocate',
    featured: true,
    name: 'Nate Soares',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/So8res',
    avatar: '/personas/soares.jpg',
    initials: 'NS',
    stance: 'Stop before we lose control.',
    tone: 'doom'
  },
  {
    id: 'empirical-control-researcher',
    featured: true,
    name: 'Ryan Greenblatt',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/RyanGreenblatt',
    avatar: '/personas/greenblatt.jpg',
    initials: 'RG',
    stance: 'Test control. Reduce takeover risk.',
    tone: 'doom'
  },
  {
    id: 'biosecurity-abundance-optimist',
    featured: true,
    name: 'Noah Smith',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/Noahpinion',
    avatar: '/personas/smith.jpg',
    initials: 'NS',
    stance: 'Build abundance. Defend against misuse.',
    tone: 'middle'
  },
  {
    id: 'control-alarmist',
    featured: true,
    name: 'Eliezer Yudkowsky',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/ESYudkowsky',
    avatar: '/personas/yudkowsky.jpg',
    initials: 'EY',
    stance: 'A future worth stopping.',
    tone: 'doom'
  },
  {
    id: 'cautious-builder',
    featured: true,
    name: 'Sam Altman',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/sama',
    avatar: '/personas/altman.jpg',
    initials: 'SA',
    stance: 'A future worth building.',
    tone: 'middle'
  },
  {
    id: 'abundance-advocate',
    featured: true,
    name: 'Marc Andreessen',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/pmarca',
    avatar: '/personas/andreessen.jpg',
    initials: 'MA',
    stance: 'A future worth accelerating.',
    tone: 'bloom'
  },
  {
    id: 'empirical-skeptic',
    featured: true,
    name: 'Gary Marcus',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/GaryMarcus',
    avatar: '/personas/marcus.jpg',
    initials: 'GM',
    stance: 'Show me that it works.',
    tone: 'doom'
  },
  {
    id: 'practical-optimist',
    featured: true,
    name: 'Andrew Ng',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/AndrewYNg',
    avatar: '/personas/ng.jpg',
    initials: 'AN',
    stance: 'Keep learning. Keep building.',
    tone: 'bloom'
  },
  {
    id: 'world-model-optimist',
    featured: true,
    name: 'Yann LeCun',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/ylecun',
    avatar: '/personas/lecun.jpg',
    initials: 'YL',
    stance: 'Intelligence needs a world model.',
    tone: 'bloom'
  },
  {
    id: 'concerned-pioneer',
    featured: true,
    name: 'Geoffrey Hinton',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/geoffreyhinton',
    avatar: '/personas/hinton.jpg',
    initials: 'GH',
    stance: 'Learn to control it first.',
    tone: 'doom'
  },
  {
    id: 'bubble-critic',
    featured: true,
    name: 'Ed Zitron',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/edzitron',
    avatar: '/personas/zitron.jpg',
    initials: 'EZ',
    stance: 'Who is this actually helping?',
    tone: 'doom'
  },
  {
    id: 'democratic-moratorium',
    featured: true,
    name: 'Bernie Sanders',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/SenSanders',
    initials: 'BS',
    stance: 'Let the public decide.',
    tone: 'doom',
    avatar: '/personas/sanders.jpg'
  },
  {
    id: 'competitive-decentralist',
    featured: true,
    name: 'David Sacks',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/DavidSacks',
    initials: 'DS',
    stance: 'Competition over gatekeepers.',
    tone: 'bloom',
    avatar: '/personas/sacks.jpg'
  },
  {
    id: 'scientific-steward',
    featured: true,
    name: 'Demis Hassabis',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/demishassabis',
    initials: 'DH',
    stance: 'A new age of discovery.',
    tone: 'bloom',
    avatar: '/personas/hassabis.jpg'
  },
  {
    id: 'coordinated-scaler',
    featured: true,
    name: 'Sholto Douglas',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/_sholtodouglas',
    initials: 'SD',
    stance: 'As fast as safety allows.',
    tone: 'bloom',
    avatar: '/personas/douglas.jpg'
  },
  {
    id: 'alignment-maximalist',
    featured: true,
    name: 'Roon',
    possessivePronoun: 'their',
    xUrl: 'https://x.com/tszzl',
    initials: 'R',
    stance: 'Pace the frontier. Solve alignment.',
    tone: 'middle',
    avatar: '/personas/roon.jpg'
  },
  {
    id: 'efficient-intelligence-builder',
    featured: true,
    name: 'Noam Shazeer',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/NoamShazeer',
    initials: 'NS',
    stance: 'Make intelligence work better.',
    tone: 'bloom',
    avatar: '/personas/shazeer.jpg'
  },
  {
    id: 'reasoning-frontier-builder',
    featured: true,
    name: 'Noam Brown',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/polynoamial',
    initials: 'NB',
    stance: 'Discover more. Test carefully.',
    tone: 'middle',
    avatar: '/personas/brown.jpg'
  },
  {
    id: 'learning-bottleneck-investigator',
    featured: true,
    name: 'Dwarkesh Patel',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/dwarkesh_sp',
    initials: 'DP',
    stance: 'What happens when AI learns on the job?',
    tone: 'middle',
    avatar: '/personas/patel.jpg'
  },
  {
    id: 'frontier-pacer',
    featured: true,
    name: 'Dario Amodei',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/DarioAmodei',
    initials: 'DA',
    stance: 'Earn the beneficial future.',
    tone: 'middle',
    avatar: '/personas/amodei.jpg'
  },
  {
    id: 'abundance-risk-taker',
    featured: true,
    name: 'Elon Musk',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/elonmusk',
    initials: 'EM',
    stance: 'Build toward extraordinary abundance.',
    tone: 'bloom',
    avatar: '/personas/musk.jpg'
  },
  {
    id: 'open-science-realist',
    featured: true,
    name: 'Nathan Lambert',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/natolambert',
    initials: 'NL',
    stance: 'Build openly. Question the takeoff story.',
    tone: 'bloom',
    avatar: '/personas/lambert.jpg'
  },
  {
    id: 'scientist-ai-advocate',
    featured: true,
    name: 'Yoshua Bengio',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/Yoshua_Bengio',
    initials: 'YB',
    stance: 'Understand the world without pursuing power.',
    tone: 'middle',
    avatar: '/personas/bengio.jpg'
  },
  {
    id: 'safe-superintelligence-researcher',
    featured: true,
    name: 'Ilya Sutskever',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/ilyasut',
    initials: 'IS',
    stance: 'Make superintelligence safe.',
    tone: 'middle',
    avatar: '/personas/sutskever.jpg'
  },
  {
    id: 'hands-on-agent-builder',
    featured: true,
    name: 'Andrej Karpathy',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/karpathy',
    initials: 'AK',
    stance: 'Build it. See where it breaks.',
    tone: 'bloom',
    avatar: '/personas/karpathy.jpg'
  },
  {
    id: 'human-centered-spatial-builder',
    featured: true,
    name: 'Fei-Fei Li',
    possessivePronoun: 'her',
    xUrl: 'https://x.com/drfeifei',
    initials: 'FL',
    stance: 'Keep people at the center.',
    tone: 'bloom',
    avatar: '/personas/li.jpg'
  },
  {
    id: 'digital-succession-optimist',
    featured: true,
    name: 'Richard Sutton',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/RichardSSutton',
    initials: 'RS',
    stance: 'Intelligence can go beyond us.',
    tone: 'bloom',
    avatar: '/personas/sutton.jpg'
  },
  {
    id: 'community-ai-critic',
    featured: true,
    name: 'Timnit Gebru',
    possessivePronoun: 'her',
    xUrl: 'https://x.com/timnitGebru',
    initials: 'TG',
    stance: 'Build for communities, not empires.',
    tone: 'doom',
    avatar: '/personas/gebru.jpg'
  },
  {
    id: 'normal-technology-realist',
    featured: true,
    name: 'Arvind Narayanan',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/random_walker',
    initials: 'AN',
    stance: 'Look at how technology actually spreads.',
    tone: 'middle',
    avatar: '/personas/narayanan.jpg'
  },
  {
    id: 'pro-worker-economist',
    featured: true,
    name: 'Daron Acemoglu',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/DAcemogluMIT',
    initials: 'DA',
    stance: 'Make progress work for workers.',
    tone: 'middle',
    avatar: '/personas/acemoglu.jpg'
  },
  {
    id: 'personal-superintelligence-builder',
    featured: true,
    name: 'Mark Zuckerberg',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/finkd',
    initials: 'MZ',
    stance: 'Put powerful AI in people’s hands.',
    tone: 'bloom',
    avatar: '/personas/zuckerberg.jpg'
  },
  {
    id: 'provable-control-advocate',
    featured: true,
    name: 'Stuart Russell',
    possessivePronoun: 'his',
    xUrl: null,
    profileUrl: 'https://people.eecs.berkeley.edu/~russell/',
    profileLabel: 'UC Berkeley',
    initials: 'SR',
    stance: 'Prove it stays under human control.',
    tone: 'doom',
    avatar: '/personas/russell.jpg'
  },
  {
    id: 'language-hype-critic',
    featured: true,
    name: 'Emily M. Bender',
    possessivePronoun: 'her',
    xUrl: 'https://x.com/emilymbender',
    initials: 'EB',
    stance: 'Fluent language is not understanding.',
    tone: 'doom',
    avatar: '/personas/bender.jpg'
  },
  {
    id: 'tool-ai-moratorium',
    featured: true,
    name: 'Max Tegmark',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/tegmark',
    initials: 'MT',
    stance: 'Build useful tools. Stop the unsafe race.',
    tone: 'doom',
    avatar: '/personas/tegmark.jpg'
  },
  {
    id: 'open-frontier-idealist',
    featured: true,
    name: 'Liang Wenfeng',
    possessivePronoun: 'his',
    xUrl: null,
    profileUrl: 'https://en.wikipedia.org/wiki/Liang_Wenfeng',
    profileLabel: 'Wikipedia',
    initials: 'LW',
    stance: 'Original research, shared openly.',
    tone: 'bloom',
    avatar: '/personas/liang.jpg'
  },
  {
    id: 'democratic-ai-steward',
    featured: true,
    name: 'Barack Obama',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/BarackObama',
    initials: 'BO',
    stance: 'Let people shape the future.',
    tone: 'middle',
    avatar: '/personas/obama.jpg'
  },
  {
    id: 'america-first-ai-booster',
    featured: true,
    name: 'Donald Trump',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/realDonaldTrump',
    initials: 'DT',
    stance: 'Build big. America must win.',
    tone: 'bloom',
    avatar: '/personas/trump.jpg'
  },
  {
    id: 'equitable-ai-philanthropist',
    featured: true,
    name: 'Bill Gates',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/BillGates',
    initials: 'BG',
    stance: 'Make breakthroughs reach everyone.',
    tone: 'bloom',
    avatar: '/personas/gates.jpg'
  },
  {
    id: 'anti-doomer',
    featured: true,
    name: 'Jensen Huang',
    possessivePronoun: 'his',
    xUrl: 'https://x.com/JensenHuang',
    initials: 'JH',
    stance: 'Reject the doomer story. Keep building.',
    tone: 'bloom',
    avatar: '/personas/huang.jpg'
  }
] as const

const catalog = [
  ...profiles.map((person) => ({
    ...person,
    ...personaIdentity(person.id)
  })),
  ...independentPersonas.map((person) => ({
    id: person.id,
    name: person.name,
    shortName: person.shortName ?? person.name,
    slug: person.slug!,
    xUsername: person.xUsername!,
    xUrl: `https://x.com/${person.xUsername}`,
    avatar: `/personas/independent-${person.xUsername}.jpg`,
    initials: person.name
      .split(/\s+/)
      .slice(0, 2)
      .map((part) => part[0])
      .join(''),
    possessivePronoun: 'their' as const,
    stance: 'A simulated worldview grounded in public sources.',
    tone: 'middle' as const,
    featured: person.featured ?? false
  })),
  {
    id: 'superintelligence-philosopher',
    name: 'Nick Bostrom',
    shortName: 'Nick Bostrom',
    slug: 'nick-bostrom',
    xUsername: null,
    xUrl: null,
    avatar: '/personas/bostrom.jpg',
    initials: 'NB',
    possessivePronoun: 'his' as const,
    stance: 'Understand the risks and the possibilities of superintelligence.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'frontier-diffusion-researcher',
    name: 'Nick Marwell',
    shortName: 'Nick Marwell',
    slug: 'the_marwell',
    xUsername: 'the_marwell',
    xUrl: 'https://x.com/the_marwell',
    avatar: '/personas/marwell.jpg',
    initials: 'NM',
    possessivePronoun: 'his' as const,
    stance: 'Realize the benefits while preparing for a difficult transition.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'joscha-bach',
    name: 'Joscha Bach',
    shortName: 'Joscha Bach',
    slug: 'plinz',
    xUsername: 'plinz',
    xUrl: 'https://x.com/Plinz',
    avatar: '/personas/bach.jpg',
    initials: 'JB',
    possessivePronoun: 'his' as const,
    stance: 'Build intelligence that helps us understand and shape the future.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'vittorio',
    name: 'Vittorio',
    shortName: 'Vittorio',
    slug: 'iterintellectus',
    xUsername: 'iterintellectus',
    xUrl: 'https://x.com/IterIntellectus',
    avatar: '/personas/vittorio.jpg',
    initials: 'V',
    possessivePronoun: 'his' as const,
    stance: 'Make intelligence abundant and human life more fulfilling.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'ramez-naam',
    name: 'Ramez Naam',
    shortName: 'Ramez Naam',
    slug: 'ramez',
    xUsername: 'ramez',
    xUrl: 'https://x.com/ramez',
    avatar: '/personas/naam.jpg',
    initials: 'RN',
    possessivePronoun: 'his' as const,
    stance: 'Expect progress. Test the feedback loop. Build safer systems.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'grady-booch',
    name: 'Grady Booch',
    shortName: 'Grady Booch',
    slug: 'grady_booch',
    xUsername: 'grady_booch',
    xUrl: 'https://x.com/Grady_Booch',
    avatar: '/personas/booch.jpg',
    initials: 'GB',
    possessivePronoun: 'his' as const,
    stance: 'Fear the billionaires, not the machines.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'subbarao-kambhampati',
    name: 'Subbarao Kambhampati',
    shortName: 'Rao Kambhampati',
    slug: 'rao2z',
    xUsername: 'rao2z',
    xUrl: 'https://x.com/rao2z',
    avatar: '/personas/kambhampati.jpg',
    initials: 'SK',
    possessivePronoun: 'his' as const,
    stance: 'Verify the plan before you act on it.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'melanie-mitchell',
    name: 'Melanie Mitchell',
    shortName: 'Melanie Mitchell',
    slug: 'melmitchell1',
    xUsername: 'melmitchell1',
    xUrl: 'https://x.com/MelMitchell1',
    avatar: '/personas/mitchell.jpg',
    initials: 'MM',
    possessivePronoun: 'her' as const,
    stance: 'Test the claims. Keep people deciding.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'thomas-dietterich',
    name: 'Thomas G. Dietterich',
    shortName: 'Thomas Dietterich',
    slug: 'tdietterich',
    xUsername: 'tdietterich',
    xUrl: 'https://x.com/tdietterich',
    avatar: '/personas/dietterich.jpg',
    initials: 'TD',
    possessivePronoun: 'his' as const,
    stance: 'Engineer for failure. Keep humans supervising.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'sayash-kapoor',
    name: 'Sayash Kapoor',
    shortName: 'Sayash Kapoor',
    slug: 'sayashk',
    xUsername: 'sayashk',
    xUrl: 'https://x.com/sayashk',
    avatar: '/personas/kapoor.jpg',
    initials: 'SK',
    possessivePronoun: 'his' as const,
    stance: 'Measure reliability. Build resilience.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'brian-merchant',
    name: 'Brian Merchant',
    shortName: 'Brian Merchant',
    slug: 'bcmerchant',
    xUsername: 'bcmerchant',
    xUrl: 'https://x.com/bcmerchant',
    avatar: '/personas/merchant.jpg',
    initials: 'BM',
    possessivePronoun: 'his' as const,
    stance: 'Ask who the machine serves.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'liron-shapira',
    name: 'Liron Shapira',
    shortName: 'Liron Shapira',
    slug: 'liron',
    xUsername: 'liron',
    xUrl: 'https://x.com/liron',
    avatar: '/personas/shapira.jpg',
    initials: 'LS',
    possessivePronoun: 'his' as const,
    stance: 'Debate the doom. Pause the race.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'rob-bensinger',
    name: 'Rob Bensinger',
    shortName: 'Rob Bensinger',
    slug: 'robbensinger',
    xUsername: 'robbensinger',
    xUrl: 'https://x.com/robbensinger',
    avatar: '/personas/bensinger.jpg',
    initials: 'RB',
    possessivePronoun: 'his' as const,
    stance: 'Halt the race. Ban superintelligence.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'ai-notkilleveryoneism-memes',
    name: 'AI Notkilleveryoneism Memes',
    shortName: 'AISafetyMemes',
    slug: 'aisafetymemes',
    xUsername: 'aisafetymemes',
    xUrl: 'https://x.com/AISafetyMemes',
    avatar: '/personas/aisafetymemes.jpg',
    initials: 'AS',
    possessivePronoun: 'their' as const,
    stance: 'Make memes. Lower p(doom).',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'holly-elmore',
    name: 'Holly Elmore',
    shortName: 'Holly Elmore',
    slug: 'ilex_ulmus',
    xUsername: 'ilex_ulmus',
    xUrl: 'https://x.com/ilex_ulmus',
    avatar: '/personas/elmore.jpg',
    initials: 'HE',
    possessivePronoun: 'her' as const,
    stance: 'Pause it now. Make them prove it is safe.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'katja-grace',
    name: 'Katja Grace',
    shortName: 'Katja Grace',
    slug: 'katjagrace',
    xUsername: 'katjagrace',
    xUrl: 'https://x.com/KatjaGrace',
    avatar: '/personas/grace.jpg',
    initials: 'KG',
    possessivePronoun: 'her' as const,
    stance: 'Pause as soon as possible. It can be done.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'kelsey-piper',
    name: 'Kelsey Piper',
    shortName: 'Kelsey Piper',
    slug: 'kelseytuoc',
    xUsername: 'kelseytuoc',
    xUrl: 'https://x.com/KelseyTuoc',
    avatar: '/personas/piper.jpg',
    initials: 'KP',
    possessivePronoun: 'her' as const,
    stance: 'Take AI seriously. Keep humans in charge.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'miles-brundage',
    name: 'Miles Brundage',
    shortName: 'Miles Brundage',
    slug: 'miles_brundage',
    xUsername: 'miles_brundage',
    xUrl: 'https://x.com/Miles_Brundage',
    avatar: '/personas/brundage.jpg',
    initials: 'MB',
    possessivePronoun: 'his' as const,
    stance: 'Verify the guardrails. Time is short.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'garrison-lovely',
    name: 'Garrison Lovely',
    shortName: 'Garrison Lovely',
    slug: 'garrisonlovely',
    xUsername: 'garrisonlovely',
    xUrl: 'https://x.com/GarrisonLovely',
    avatar: '/personas/lovely.jpg',
    initials: 'GL',
    possessivePronoun: 'his' as const,
    stance: 'Stop the race to replace us.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'oliver-habryka',
    name: 'Oliver Habryka',
    shortName: 'Oliver Habryka',
    slug: 'ohabryka',
    xUsername: 'ohabryka',
    xUrl: 'https://x.com/ohabryka',
    avatar: '/personas/habryka.jpg',
    initials: 'OH',
    possessivePronoun: 'his' as const,
    stance: "Don't build AGI for a long time.",
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'ajeya-cotra',
    name: 'Ajeya Cotra',
    shortName: 'Ajeya Cotra',
    slug: 'ajeya_cotra',
    xUsername: 'ajeya_cotra',
    xUrl: 'https://x.com/ajeya_cotra',
    avatar: '/personas/cotra.jpg',
    initials: 'AC',
    possessivePronoun: 'her' as const,
    stance: 'Measure the risk. Publish the evidence.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'bayeslord',
    name: 'bayes',
    shortName: 'bayes',
    slug: 'bayeslord',
    xUsername: 'bayeslord',
    xUrl: 'https://x.com/bayeslord',
    avatar: '/personas/bayeslord.jpg',
    initials: 'BA',
    possessivePronoun: 'their' as const,
    stance: 'Take the risks seriously. Share the safety work.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'balaji-srinivasan',
    name: 'Balaji Srinivasan',
    shortName: 'Balaji Srinivasan',
    slug: 'balajis',
    xUsername: 'balajis',
    xUrl: 'https://x.com/balajis',
    avatar: '/personas/srinivasan.jpg',
    initials: 'BS',
    possessivePronoun: 'his' as const,
    stance: 'Keep AI on the leash. Decentralize it.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'martin-casado',
    name: 'Martin Casado',
    shortName: 'Martin Casado',
    slug: 'martin_casado',
    xUsername: 'martin_casado',
    xUrl: 'https://x.com/martin_casado',
    avatar: '/personas/casado.jpg',
    initials: 'MC',
    possessivePronoun: 'his' as const,
    stance: 'Find the real risk. Regulate the use.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'richard-hanania',
    name: 'Richard Hanania',
    shortName: 'Richard Hanania',
    slug: 'richardhanania',
    xUsername: 'richardhanania',
    xUrl: 'https://x.com/RichardHanania',
    avatar: '/personas/hanania.jpg',
    initials: 'RH',
    possessivePronoun: 'his' as const,
    stance: 'Trust the base rates, not the panic.',
    tone: 'bloom' as const,
    featured: false
  },
  {
    id: 'kevin-roose',
    name: 'Kevin Roose',
    shortName: 'Kevin Roose',
    slug: 'kevinroose',
    xUsername: 'kevinroose',
    xUrl: 'https://x.com/kevinroose',
    avatar: '/personas/roose.jpg',
    initials: 'KR',
    possessivePronoun: 'his' as const,
    stance: 'Take AI seriously. Use the window.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'casey-newton',
    name: 'Casey Newton',
    shortName: 'Casey Newton',
    slug: 'caseynewton',
    xUsername: 'caseynewton',
    xUrl: 'https://x.com/CaseyNewton',
    avatar: '/personas/newton.jpg',
    initials: 'CN',
    possessivePronoun: 'his' as const,
    stance: 'AI is real and dangerous.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'rob-wiblin',
    name: 'Rob Wiblin',
    shortName: 'Rob Wiblin',
    slug: 'robertwiblin',
    xUsername: 'robertwiblin',
    xUrl: 'https://x.com/robertwiblin',
    avatar: '/personas/wiblin.jpg',
    initials: 'RW',
    possessivePronoun: 'his' as const,
    stance: 'Read the evidence carefully. Then slow down.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'nathan-labenz',
    name: 'Nathan Labenz',
    shortName: 'Nathan Labenz',
    slug: 'labenz',
    xUsername: 'labenz',
    xUrl: 'https://x.com/labenz',
    avatar: '/personas/labenz.jpg',
    initials: 'NL',
    possessivePronoun: 'his' as const,
    stance: 'Aim for shared abundance, not an AI race.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'aella',
    name: 'Aella',
    shortName: 'Aella',
    slug: 'aella_girl',
    xUsername: 'aella_girl',
    xUrl: 'https://x.com/Aella_Girl',
    avatar: '/personas/aella.jpg',
    initials: 'AE',
    possessivePronoun: 'her' as const,
    stance: 'Pause the race. Say it plainly.',
    tone: 'doom' as const,
    featured: false
  },
  {
    id: 'cory-doctorow-public',
    name: 'Cory Doctorow',
    shortName: 'Cory Doctorow',
    slug: 'cory-doctorow',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://craphound.com/',
    profileLabel: 'Author website',
    avatar: '/personas/doctorow.jpg',
    initials: 'CD',
    possessivePronoun: 'his' as const,
    stance: 'Useful tools. Worker power. Corporate accountability.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'ha-joon-chang-public',
    name: 'Ha-Joon Chang',
    shortName: 'Ha-Joon Chang',
    slug: 'ha-joon-chang',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://www.soas.ac.uk/about/ha-joon-chang',
    profileLabel: 'SOAS',
    avatar: '/personas/chang.jpg',
    initials: 'HC',
    possessivePronoun: 'his' as const,
    stance: 'Public choices should shape AI’s uses and benefits.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'ted-chiang-public',
    name: 'Ted Chiang',
    shortName: 'Ted Chiang',
    slug: 'ted-chiang',
    xUsername: null,
    xUrl: null,
    avatar: '/personas/chiang.jpg',
    initials: 'TC',
    possessivePronoun: 'his' as const,
    stance: 'Human choices, creativity and responsibility.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'paul-krugman-public',
    name: 'Paul Krugman',
    shortName: 'Paul Krugman',
    slug: 'paul-krugman',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://paulkrugman.substack.com/',
    profileLabel: 'Newsletter',
    avatar: '/personas/krugman.jpg',
    initials: 'PK',
    possessivePronoun: 'his' as const,
    stance: 'Economic returns, public welfare and AI safeguards.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'naomi-klein-public',
    name: 'Naomi Klein',
    shortName: 'Naomi Klein',
    slug: 'naomi-klein',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://naomiklein.org/',
    profileLabel: 'Author website',
    avatar: '/personas/klein.jpg',
    initials: 'NK',
    possessivePronoun: 'her' as const,
    stance: 'Protect people, democratic power and the climate.',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'jon-stewart-public',
    name: 'Jon Stewart',
    shortName: 'Jon Stewart',
    slug: 'jon-stewart',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://www.cc.com/shows/the-daily-show',
    profileLabel: 'The Daily Show',
    avatar: '/personas/stewart.jpg',
    initials: 'JS',
    possessivePronoun: 'his' as const,
    stance: 'Who decides, who benefits, and what happens to work?',
    tone: 'middle' as const,
    featured: false
  },
  {
    id: 'elizabeth-warren-public',
    name: 'Elizabeth Warren',
    shortName: 'Elizabeth Warren',
    slug: 'elizabeth-warren',
    xUsername: null,
    xUrl: null,
    profileUrl: 'https://www.warren.senate.gov/',
    profileLabel: 'Senate website',
    avatar: '/personas/warren.jpg',
    initials: 'EW',
    possessivePronoun: 'her' as const,
    stance: 'Set safeguards. Share benefits. Protect the public.',
    tone: 'middle' as const,
    featured: false
  },
  ...techPosterPersonas.map((person) => ({
    id: person.id,
    name: person.name,
    shortName: person.shortName ?? person.name,
    slug: person.slug!,
    xUsername: person.xUsername!,
    xUrl: `https://x.com/${person.xUsername}`,
    avatar: `/personas/${person.slug}.jpg`,
    initials: person.name
      .split(/\s+/)
      .slice(0, 2)
      .map((part) => part[0])
      .join('')
      .toUpperCase(),
    possessivePronoun: techPosterPronouns[person.slug!] ?? ('their' as const),
    stance: 'A simulated worldview grounded in public sources.',
    tone: 'middle' as const,
    featured: false
  }))
]

// One-liners live in one file, under the rule that governs how we describe
// real people.
const featuredIndependentIds = new Set([
  'independent-simonw',
  'independent-thestalwart',
  'independent-badlogicgames'
])

export const people = catalog.map((person) => ({
  ...person,
  featured: person.featured || featuredIndependentIds.has(person.id),
  description: oneLiner(person.slug)
}))
